name: 每日更新clash.yaml文件
on:
  schedule:
    # 每天UTC时间0点运行，北京时间为上午8点
    - cron: '0 0 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  update-clash-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码仓库
        uses: actions/checkout@v4

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 生成当日URL并保存到clash.yaml
        run: |
          import os
          from datetime import datetime

          # 获取当前日期，格式为YYYYMMDD
          current_date = datetime.now().strftime("%Y%m%d")
          print(f"当前日期: {current_date}")
          
          # URL模板列表
          url_templates = [
              "https://node.freeclashnode.com/uploads/{year}/{month}/0-{date}.yaml",
              "https://node.freeclashnode.com/uploads/{year}/{month}/1-{date}.yaml",
              "https://node.freeclashnode.com/uploads/{year}/{month}/2-{date}.yaml",
              "https://node.freeclashnode.com/uploads/{year}/{month}/3-{date}.yaml",
              "https://node.freeclashnode.com/uploads/{year}/{month}/4-{date}.yaml",
              "http://mlfenx.cczzuu.top/node/{date}-clash.yaml",
              "http://clashshare.cczzuu.top/node/{date}-clash.yaml",
              "https://node.openclash.cc/uploads/{year}/{month}/0-{date}.yaml",
              "https://node.openclash.cc/uploads/{year}/{month}/1-{date}.yaml",
              "https://node.openclash.cc/uploads/{year}/{month}/2-{date}.yaml",
              "https://node.openclash.cc/uploads/{year}/{month}/3-{date}.yaml",
              "https://node.openclash.cc/uploads/{year}/{month}/4-{date}.yaml",
              "https://node.freeclashverge.com/uploads/{year}/{month}/0-{date}.yaml",
              "https://node.freeclashverge.com/uploads/{year}/{month}/1-{date}.yaml",
              "https://node.freeclashverge.com/uploads/{year}/{month}/2-{date}.yaml",
              "https://node.freeclashverge.com/uploads/{year}/{month}/4-{date}.yaml",
              "https://free.datiya.com/uploads/{date}-clash.yaml"
          ]
          
          # 解析年、月
          year = current_date[:4]
          month = current_date[4:6]
          
          # 生成纯URL内容，每个URL单独一行
          content = ""
          for template in url_templates:
              url = template.format(year=year, month=month, date=current_date)
              content += f"{url}\n"
          
          # 保存到仓库根目录的clash.yaml
          with open('clash.yaml', 'w', encoding='utf-8') as f:
              f.write(content)
          
          print("已生成当日最新的clash.yaml文件")

        shell: python {0}

      - name: 提交更新
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add clash.yaml
          git commit -m "每日自动更新clash.yaml: $(date +'%Y-%m-%d')" || echo "clash.yaml没有更新内容"
          git push
    
