name: 每日合并链接内容到v2.txt
on:
  schedule:
    # 每天UTC时间0点运行，北京时间为上午8点
    - cron: '0 0 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  update-v2txt:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码仓库
        uses: actions/checkout@v4

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: pip install requests

      - name: 收集并合并内容到v2.txt
        run: |
          import os
          import requests
          from datetime import datetime

          # 获取当前日期，格式为YYYYMMDD
          current_date = datetime.now().strftime("%Y%m%d")
          print(f"当前日期: {current_date}")
          
          # 要下载的文件URL模板列表
          url_templates = [
              "https://node.freeclashnode.com/uploads/{year}/{month}/0-{date}.txt",
              "https://node.freeclashnode.com/uploads/{year}/{month}/1-{date}.txt",
              "https://node.freeclashnode.com/uploads/{year}/{month}/2-{date}.txt",
              "https://node.freeclashnode.com/uploads/{year}/{month}/3-{date}.txt",
              "https://node.freeclashnode.com/uploads/{year}/{month}/4-{date}.txt",
              "http://mlfenx.cczzuu.top/node/{date}-v2ray.txt",
              "http://clashshare.cczzuu.top/node/{date}-v2ray.txt",
              "https://node.openclash.cc/uploads/{year}/{month}/0-{date}.txt",
              "https://node.openclash.cc/uploads/{year}/{month}/1-{date}.txt",
              "https://node.freeclashverge.com/uploads/{year}/{month}/0-{date}.txt",
              "https://node.freeclashverge.com/uploads/{year}/{month}/1-{date}.txt",
              "https://node.freeclashverge.com/uploads/{year}/{month}/3-{date}.txt",
              "https://free.datiy.com/uploads/{date}-v2ray.txt"
          ]
          
          # 解析年、月
          year = current_date[:4]
          month = current_date[4:6]
          
          # 准备v2.txt的内容
          content = f"===== 自动更新于 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} =====\n\n"
          
          # 为每个URL模板生成实际URL并获取内容
          for i, template in enumerate(url_templates):
              try:
                  # 替换模板中的占位符
                  url = template.format(year=year, month=month, date=current_date)
                  print(f"正在处理: {url}")
                  
                  # 发送请求
                  response = requests.get(url, timeout=10)
                  response.raise_for_status()  # 检查请求是否成功
                  
                  # 添加内容到合并结果，包含来源标识
                  content += f"===== 来源 {i+1}: {url} =====\n"
                  content += response.text + "\n\n"
                  
              except Exception as e:
                  print(f"处理失败 {url}: {str(e)}")
                  content += f"===== 来源 {i+1}: {url} (获取失败) =====\n"
                  content += f"错误信息: {str(e)}\n\n"
          
          # 保存合并后的内容到v2.txt
          with open('v2.txt', 'w', encoding='utf-8') as f:
              f.write(content)
          
          print("已将所有内容合并到v2.txt")

        shell: python {0}

      - name: 提交更新
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add v2.txt
          git commit -m "每日自动更新v2.txt: $(date +'%Y-%m-%d')" || echo "v2.txt没有更新内容"
          git push
    
