name: 每日收集原始URL到123.txt
on:
  schedule:
    # 每天UTC时间0点运行，北京时间为上午8点
    - cron: '0 0 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  collect-urls:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码仓库
        uses: actions/checkout@v4

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 生成并保存当日URL到123.txt
        run: |
          import os
          from datetime import datetime

          # 获取当前日期，格式为YYYYMMDD
          current_date = datetime.now().strftime("%Y%m%d")
          print(f"当前日期: {current_date}")
          
          # URL模板列表
          url_templates = [
              "https://node.freeclashnode.com/uploads/{year}/{month}/0-{date}.txt",
              "https://node.freeclashnode.com/uploads/{year}/{month}/1-{date}.txt",
              "https://node.freeclashnode.com/uploads/{year}/{month}/2-{date}.txt",
              "https://node.freeclashnode.com/uploads/{year}/{month}/3-{date}.txt",
              "https://node.freeclashnode.com/uploads/{year}/{month}/4-{date}.txt",
              "http://mlfenx.cczzuu.top/node/{date}-v2ray.txt",
              "http://clashshare.cczzuu.top/node/{date}-v2ray.txt",
              "https://node.openclash.cc/uploads/{year}/{month}/0-{date}.txt",
              "https://node.openclash.cc/uploads/{year}/{month}/1-{date}.txt",
              "https://node.freeclashverge.com/uploads/{year}/{month}/0-{date}.txt",
              "https://node.freeclashverge.com/uploads/{year}/{month}/1-{date}.txt",
              "https://node.freeclashverge.com/uploads/{year}/{month}/3-{date}.txt",
              "https://free.datiy.com/uploads/{date}-v2ray.txt"
          ]
          
          # 解析年、月
          year = current_date[:4]
          month = current_date[4:6]
          
          # 准备123.txt的内容
          content = f"===== 自动更新于 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} =====\n\n"
          
          # 为每个URL模板生成实际URL并添加到内容中
          for i, template in enumerate(url_templates):
              # 替换模板中的占位符
              url = template.format(year=year, month=month, date=current_date)
              content += f"{url}\n"
          
          # 保存URL列表到123.txt
          with open('123.txt', 'w', encoding='utf-8') as f:
              f.write(content)
          
          print("已将所有当日URL保存到123.txt")

        shell: python {0}

      - name: 提交更新
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add 123.txt
          git commit -m "每日自动更新URL列表: $(date +'%Y-%m-%d')" || echo "URL列表没有更新"
          git push
    
