name: 每日生成v2ray相关文件
on:
  schedule:
    # 每天UTC时间0点运行，北京时间为上午8点
    - cron: '0 0 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  generate-v2ray-files:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码仓库
        uses: actions/checkout@v4

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: pip install requests urllib3

      - name: 生成URL列表、内容合并文件和单独文件
        run: |
          import os
          import requests
          from datetime import datetime
          from requests.adapters import HTTPAdapter
          from urllib3.util.retry import Retry

          # 配置请求重试机制和浏览器头信息
          def create_session_with_retry(retries=3, backoff_factor=0.3):
              session = requests.Session()
              
              # 添加浏览器请求头，模拟正常访问
              session.headers = {
                  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
                  'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
                  'Accept-Language': 'zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3',
                  'Connection': 'keep-alive',
                  'Upgrade-Insecure-Requests': '1'
              }
              
              # 配置重试策略
              retry = Retry(
                  total=retries,
                  read=retries,
                  connect=retries,
                  backoff_factor=backoff_factor,
                  status_forcelist=(429, 500, 502, 504)
              )
              adapter = HTTPAdapter(max_retries=retry)
              session.mount('http://', adapter)
              session.mount('https://', adapter)
              return session

          # 获取当前日期，格式为YYYYMMDD
          current_date = datetime.now().strftime("%Y%m%d")
          print(f"当前日期: {current_date}")
          
          # 要处理的文件URL模板列表
          url_templates = [
              "https://node.freeclashnode.com/uploads/{year}/{month}/0-{date}.txt",
              "https://node.freeclashnode.com/uploads/{year}/{month}/1-{date}.txt",
              "https://node.freeclashnode.com/uploads/{year}/{month}/2-{date}.txt",
              "https://node.freeclashnode.com/uploads/{year}/{month}/3-{date}.txt",
              "https://node.freeclashnode.com/uploads/{year}/{month}/4-{date}.txt",
              "http://mlfenx.cczzuu.top/node/{date}-v2ray.txt",
              "http://clashshare.cczzuu.top/node/{date}-v2ray.txt",
              "https://node.openclash.cc/uploads/{year}/{month}/0-{date}.txt",
              "https://node.openclash.cc/uploads/{year}/{month}/1-{date}.txt",
              "https://node.freeclashverge.com/uploads/{year}/{month}/0-{date}.txt",
              "https://node.freeclashverge.com/uploads/{year}/{month}/1-{date}.txt",
              "https://node.freeclashverge.com/uploads/{year}/{month}/3-{date}.txt"
          ]
          
          # 解析年、月
          year = current_date[:4]
          month = current_date[4:6]
          
          # 生成实际URL列表
          urls = [template.format(year=year, month=month, date=current_date) for template in url_templates]
          
          # 1. 生成纯URL文件 v2rayno.txt（仅URL，无额外内容）
          with open('v2rayno.txt', 'w', encoding='utf-8') as f:
              for url in urls:
                  f.write(f"{url}\n")
          
          # 2. 准备内容合并文件 v2ray.txt 的内容
          content = f"===== 自动更新于 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} =====\n\n"
          
          # 创建带有重试机制的会话
          session = create_session_with_retry()
          
          # 为每个URL获取内容并处理
          for i, url in enumerate(urls):
              try:
                  print(f"正在处理: {url}")
                  
                  # 发送请求
                  response = session.get(url, timeout=15)
                  response.raise_for_status()  # 检查请求是否成功
                  
                  # 添加内容到合并结果，包含来源标识
                  content += f"===== 来源 {i+1}: {url} =====\n"
                  content += response.text + "\n\n"
                  
                  # 3. 为每个链接生成单独文件
                  filename = f"v2ray-{i+1}.txt"
                  with open(filename, 'w', encoding='utf-8') as single_file:
                      single_file.write(f"===== 来源 {i+1}: {url} =====\n")
                      single_file.write(f"===== 获取时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} =====\n\n")
                      single_file.write(response.text)
                  print(f"已生成单独文件: {filename}")
                  
              except Exception as e:
                  print(f"处理失败 {url}: {str(e)}")
                  content += f"===== 来源 {i+1}: {url} (获取失败) =====\n"
                  content += f"错误信息: {str(e)}\n\n"
                  
                  # 即使失败也生成包含错误信息的单独文件
                  filename = f"v2ray-{i+1}.txt"
                  with open(filename, 'w', encoding='utf-8') as single_file:
                      single_file.write(f"===== 来源 {i+1}: {url} (获取失败) =====\n")
                      single_file.write(f"===== 获取时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} =====\n\n")
                      single_file.write(f"错误信息: {str(e)}\n")
                  continue  # 继续处理下一个链接
          
          # 保存合并后的内容到v2ray.txt
          with open('v2ray.txt', 'w', encoding='utf-8') as f:
              f.write(content)
          
          print("已生成v2rayno.txt、v2ray.txt文件和所有单独文件")

        shell: python {0}

      - name: 提交更新
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add v2rayno.txt v2ray.txt v2ray-*.txt
          git commit -m "每日自动更新v2ray相关文件: $(date +'%Y-%m-%d')" || echo "没有更新内容"
          git push
